### ISSUE TITLE
"issubclass() arg 1 must be a class" on newer version of Gradio

### ISSUE THREAD

**Issue by gruberdev** [hwchase17/langchain-gradio-template#3]
## Description

On a clean environment, when installing the newest version of Gradio, the following error happens when trying to run the application with `python app.py`:

```sh
Traceback (most recent call last):
File "/home/Folder_1c8df4/Projects/Folder_4f2a67/Folder_b1e6c2/app.py", line 101, in <module>
submit.click(chat, inputs=[openai_api_key_textbox, message,
File "/home/Folder_1c8df4/.conda/Folder_9d3ba1/lib/python3.9/site-packages/gradio/events.py", line 132, in call
dep, dep_index = self.trigger.set_event_trigger(
File "/home/Folder_1c8df4/.conda/Folder_9d3ba1/lib/python3.9/site-packages/gradio/blocks.py", line 217, in set_event_trigger
check_function_inputs_match(fn, inputs, inputs_as_dict)
File "/home/Folder_1c8df4/.conda/Folder_9d3ba1/lib/python3.9/site-packages/gradio/utils.py", line 872, in check_function_inputs_match
if not is_special_typed_parameter(name):
File "/home/Folder_1c8df4/.conda/Folder_9d3ba1/lib/python3.9/site-packages/gradio/utils.py", line 861, in is_special_typed_parameter
is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class
```

This happens in both Python 3.9 and 3.11. When searching for the source of the problem, I happened to find this related issue: https://github.com/gradio-app/gradio/issues/3514

Given the date it happened, I downgraded my Gradio from 3.28.3 to 3.19.1, to investigate it might be related to Gradio versioning, and it ran without any problems. 

I advise that the version for Gradio is pinned until this error is fixed, either in Gradio itself or in the code of this repository.

**Comment by gruberdev** [comment]
This bug has been resolved on Gradio 3.29.0. Closing this issue.
